### Buscar todas as categorias
GET http://localhost:3000/reservation

### Buscar categoria por ID
GET http://localhost:3000/reservation/1

### Criar nova categoria
POST http://localhost:3000/reservation
Content-Type: application/json

{
  "id_users": "7",
  "id_classroom": "7",
  "data_reservation": "05/10/25",
  "hora_inicio": "10:50",
  "hora_fim": "11:50",
  "id_status": "18"
}

### Atualizar categoria
PUT http://localhost:3000/reservation/1
Content-Type: application/json

{
    "id_users": "2",
    "id_classroom": "2",
    "data_reservation": "05/10/25",
    "hora_inicio": "10:50",
    "hora_fim": "11:50",
    "id_status": "1"
  
}

### Deletar categoria
DELETE http://localhost:3000/reservation/7