### Buscar todas as categorias
GET http://localhost:3000/status_reservation

### Buscar categoria por ID
GET http://localhost:3000/status_reservation/18

### Criar nova categoria
POST http://localhost:3000/status_reservation
Content-Type: application/json

{
  "descricao": "ocupada"

}

### Atualizar categoria
PUT http://localhost:3000/status_reservation/17
Content-Type: application/json

{
  "descricao": "Livre"

}

### Deletar categoria
DELETE http://localhost:3000/status_reservation/17