### Buscar todas as categorias
GET http://localhost:3000/classroom

### Buscar categoria por ID
GET http://localhost:3000/classroom/1

### Criar nova categoria
POST http://localhost:3000/classroom
Content-Type: application/json

{
  "nome": "M1",
  "capacidade": 20,
  "localizacao": "Segundo"
  
}

### Atualizar categoria
PUT http://localhost:3000/classroom/3
Content-Type: application/json

{
  "nome": "A2",
  "capacidade": 5,
  "localizacao": "Primeiro"
  
}

### Deletar categoria
DELETE http://localhost:3000/classroom/1